import { useEffect, useState } from 'react'
import {
  ArrowDown,
  ChevronDown,
  ChevronRight,
  FileText,
  Loader2,
  Workflow,
} from 'lucide-react'
import { Badge } from '@embeddr/react-ui/ui'
import { embeddrApi } from '@/lib/api/client'
import type {
  ProvenanceResponse,
  ProvenanceStep,
  ProvenanceSource,
  ProvenanceAnnotation,
} from '@/lib/api/types'
import type { PromptImage } from '@embeddr/react-ui/types'

interface ProvenanceTimelineProps {
  artifactId: string
  onSelectArtifact?: (image: PromptImage) => void
}

function SourceBadge({ source }: { source: ProvenanceSource }) {
  return (
    <div className="flex items-center gap-1.5">
      {source.icon_url ? (
        <img
          src={source.icon_url}
          alt=""
          className="w-3.5 h-3.5 rounded-sm object-contain"
        />
      ) : (
        <Workflow className="w-3 h-3 text-muted-foreground" />
      )}
      <span className="text-[10px] font-medium text-muted-foreground">
        {source.name}
      </span>
    </div>
  )
}

function RelationLabel({ type }: { type?: string | null }) {
  if (!type) return null
  const labels: Record<string, string> = {
    generates: 'generated',
    generated_by: 'generated by',
    reference: 'referenced',
    part_of: 'part of',
    variant_of: 'variant of',
    derived_from: 'derived from',
    lineage: 'linked',
  }
  return (
    <span className="text-[10px] text-muted-foreground/70 italic">
      {labels[type] || type}
    </span>
  )
}

const ANNOTATION_LABELS: Record<string, string> = {
  'comfyui:workflow_inputs': 'Workflow Inputs',
  'generation_params': 'Generation Parameters',
  'caption': 'Caption',
  'prompt': 'Prompt',
  'summary': 'Summary',
}

function AnnotationCard({ annotation }: { annotation: ProvenanceAnnotation }) {
  const [expanded, setExpanded] = useState(false)
  const label = ANNOTATION_LABELS[annotation.annotation_type] || annotation.annotation_type
  const hasData = annotation.data && Object.keys(annotation.data).length > 0

  // For structured data (JSON), show key-value pairs
  // For plain text, show the text
  const content = hasData ? annotation.data : null
  const plainText = !hasData ? annotation.text : null

  // Filter out internal/noisy keys from display
  const displayEntries = content
    ? Object.entries(content).filter(([key]) =>
        !['execution_id', 'prompt_id'].includes(key)
      )
    : []

  return (
    <div className="border border-border/40 rounded-lg overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-2 px-3 py-2 text-left hover:bg-muted/30 transition-colors"
      >
        <FileText className="w-3 h-3 text-muted-foreground flex-shrink-0" />
        <span className="text-[11px] font-medium flex-1">{label}</span>
        {annotation.plugin_name && (
          <span className="text-[9px] text-muted-foreground/60">
            {annotation.plugin_name}
          </span>
        )}
        {expanded
          ? <ChevronDown className="w-3 h-3 text-muted-foreground/50" />
          : <ChevronRight className="w-3 h-3 text-muted-foreground/50" />
        }
      </button>
      {expanded && (
        <div className="px-3 pb-2 pt-0">
          {displayEntries.length > 0 ? (
            <div className="text-[10px] space-y-1">
              {displayEntries.map(([key, value]) => (
                <div key={key} className="grid grid-cols-3 gap-1.5">
                  <span className="text-muted-foreground font-medium truncate">
                    {key}
                  </span>
                  <span className="col-span-2 font-mono text-muted-foreground/80 break-all whitespace-pre-wrap">
                    {typeof value === 'object'
                      ? JSON.stringify(value, null, 2)
                      : String(value ?? '')}
                  </span>
                </div>
              ))}
            </div>
          ) : plainText ? (
            <div className="text-[10px] text-muted-foreground/80 font-mono whitespace-pre-wrap break-all max-h-40 overflow-y-auto">
              {plainText}
            </div>
          ) : (
            <div className="text-[10px] text-muted-foreground/50 italic">
              No data
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function StepCard({
  step,
  isSelf,
  onSelect,
}: {
  step: ProvenanceStep
  isSelf?: boolean
  onSelect?: (image: PromptImage) => void
}) {
  const art = step.artifact
  const previewUrl = embeddrApi.artifacts.getPreviewUrl(art.id, 'thumbnail')

  const handleClick = () => {
    if (isSelf || !onSelect) return
    onSelect({
      id: art.id,
      url: embeddrApi.artifacts.getContentUrl(art.id),
      image_url: embeddrApi.artifacts.getContentUrl(art.id),
      thumb_url: previewUrl,
      width: 0,
      height: 0,
      prompt: '',
      created_at: art.created_at || '',
    })
  }

  return (
    <div
      className={`
        flex items-start gap-3 p-2.5 rounded-lg border transition-all
        ${isSelf
          ? 'border-primary/30 bg-primary/5 ring-1 ring-primary/20'
          : 'border-border/50 hover:border-border hover:bg-muted/30 cursor-pointer'
        }
      `}
      onClick={handleClick}
    >
      <div className="w-10 h-10 rounded-md border border-border/50 overflow-hidden flex-shrink-0 bg-muted">
        <img
          src={previewUrl}
          alt=""
          className="w-full h-full object-cover"
          loading="lazy"
        />
      </div>
      <div className="flex-1 min-w-0 space-y-0.5">
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium truncate">
            {art.name || art.id.slice(-8)}
          </span>
          {isSelf && (
            <Badge variant="outline" className="text-[9px] h-4 px-1.5 flex-shrink-0">
              this
            </Badge>
          )}
          {!isSelf && (
            <ChevronRight className="w-3 h-3 text-muted-foreground/40 flex-shrink-0" />
          )}
        </div>
        <div className="flex items-center gap-2">
          {step.source && <SourceBadge source={step.source} />}
          <RelationLabel type={step.relation_type} />
        </div>
        {art.created_at && (
          <div className="text-[10px] text-muted-foreground/60">
            {new Date(art.created_at).toLocaleDateString(undefined, {
              month: 'short',
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
            })}
          </div>
        )}
      </div>
    </div>
  )
}

function Connector({ label }: { label?: string }) {
  return (
    <div className="flex flex-col items-center py-1">
      <div className="w-px h-3 bg-border" />
      <ArrowDown className="w-3 h-3 text-muted-foreground/40" />
      {label && (
        <span className="text-[9px] text-muted-foreground/50 -mt-0.5">
          {label}
        </span>
      )}
    </div>
  )
}

export function ProvenanceTimeline({
  artifactId,
  onSelectArtifact,
}: ProvenanceTimelineProps) {
  const [data, setData] = useState<ProvenanceResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!artifactId) return
    setLoading(true)
    setError(null)
    embeddrApi.artifacts
      .getProvenance(artifactId)
      .then(setData)
      .catch((e) => setError(e?.message || 'Failed to load provenance'))
      .finally(() => setLoading(false))
  }, [artifactId])

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8 text-muted-foreground">
        <Loader2 className="w-4 h-4 animate-spin mr-2" />
        <span className="text-xs">Loading provenance...</span>
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-xs text-muted-foreground italic py-4 text-center">
        {error}
      </div>
    )
  }

  if (!data) return null

  const hasInputs = data.inputs.length > 0
  const hasOutputs = data.outputs.length > 0
  const hasRelations = data.relations.length > 0
  const hasAnnotations = data.annotations && data.annotations.length > 0
  const isEmpty = !hasInputs && !hasOutputs && !hasRelations && !hasAnnotations && !data.creation_execution

  if (isEmpty) {
    return (
      <div className="text-xs text-muted-foreground italic py-2">
        No provenance data available
      </div>
    )
  }

  // Build the self step
  const selfStep: ProvenanceStep = {
    artifact: data.artifact,
    role: 'self',
    depth: 0,
    source: data.sources.length > 0 ? data.sources[0] : null,
  }

  return (
    <div className="space-y-0">
      {/* Source badges */}
      {data.sources.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-3">
          {data.sources.map((s) => (
            <div
              key={s.namespace}
              className="flex items-center gap-1.5 px-2 py-1 rounded-full bg-muted/50 border border-border/50"
            >
              {s.icon_url ? (
                <img src={s.icon_url} alt="" className="w-3.5 h-3.5 rounded-sm object-contain" />
              ) : (
                <Workflow className="w-3 h-3 text-muted-foreground" />
              )}
              <span className="text-[10px] font-medium">{s.name}</span>
            </div>
          ))}
        </div>
      )}

      {/* Inputs (parents) */}
      {hasInputs && (
        <>
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground/60 font-medium mb-1.5">
            Inputs
          </div>
          <div className="space-y-1.5">
            {data.inputs.map((step, i) => (
              <StepCard
                key={`in-${step.artifact.id}-${i}`}
                step={step}
                onSelect={onSelectArtifact}
              />
            ))}
          </div>
          <Connector label="used to create" />
        </>
      )}

      {/* Self (the artifact) */}
      <StepCard step={selfStep} isSelf />

      {/* Creation execution info */}
      {data.creation_execution && (
        <div className="ml-4 mt-1 mb-1 flex items-center gap-2 text-[10px] text-muted-foreground/60">
          <Workflow className="w-3 h-3" />
          <span>
            {data.creation_execution.plugin_name} / {data.creation_execution.type}
          </span>
          {data.creation_execution.finished_at && (
            <span>
              {new Date(data.creation_execution.finished_at).toLocaleDateString()}
            </span>
          )}
        </div>
      )}

      {/* Annotations (workflow inputs, generation params, etc.) */}
      {hasAnnotations && (
        <div className="mt-2 space-y-1.5">
          {data.annotations.map((ann, i) => (
            <AnnotationCard key={`ann-${ann.id}-${i}`} annotation={ann} />
          ))}
        </div>
      )}

      {/* Outputs (children) */}
      {hasOutputs && (
        <>
          <Connector label="produced" />
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground/60 font-medium mb-1.5">
            Outputs
          </div>
          <div className="space-y-1.5">
            {data.outputs.map((step, i) => (
              <StepCard
                key={`out-${step.artifact.id}-${i}`}
                step={step}
                onSelect={onSelectArtifact}
              />
            ))}
          </div>
        </>
      )}

      {/* Semantic relations */}
      {hasRelations && (
        <>
          <div className="mt-3 pt-3 border-t border-border/30">
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground/60 font-medium mb-1.5">
              Related
            </div>
            <div className="space-y-1.5">
              {data.relations.map((step, i) => (
                <StepCard
                  key={`rel-${step.artifact.id}-${i}`}
                  step={step}
                  onSelect={onSelectArtifact}
                />
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  )
}
