/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UmapRouteImport } from './routes/umap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LotusPlaygroundRouteImport } from './routes/lotus-playground'
import { Route as LotusRouteImport } from './routes/lotus'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines.index'
import { Route as ActionsIndexRouteImport } from './routes/actions.index'
import { Route as PluginsActionsRouteImport } from './routes/plugins.actions'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins.$pluginId'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines.$pipelineId'
import { Route as ImagesImageIdRouteImport } from './routes/images.$imageId'
import { Route as ActionsActionIdRouteImport } from './routes/actions.$actionId'
import { Route as PluginsPluginIdPageIdRouteImport } from './routes/plugins.$pluginId.$pageId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UmapRoute = UmapRouteImport.update({
  id: '/umap',
  path: '/umap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LotusPlaygroundRoute = LotusPlaygroundRouteImport.update({
  id: '/lotus-playground',
  path: '/lotus-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LotusRoute = LotusRouteImport.update({
  id: '/lotus',
  path: '/lotus',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelinesRoute,
} as any)
const ActionsIndexRoute = ActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsActionsRoute = PluginsActionsRouteImport.update({
  id: '/plugins/actions',
  path: '/plugins/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/$pipelineId',
  path: '/$pipelineId',
  getParentRoute: () => PipelinesRoute,
} as any)
const ImagesImageIdRoute = ImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsActionIdRoute = ActionsActionIdRouteImport.update({
  id: '/actions/$actionId',
  path: '/actions/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdPageIdRoute = PluginsPluginIdPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => PluginsPluginIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/authorize': typeof AuthorizeRoute
  '/datasets': typeof DatasetsRoute
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/lineage': typeof LineageRoute
  '/lotus': typeof LotusRoute
  '/lotus-playground': typeof LotusPlaygroundRoute
  '/onboarding': typeof OnboardingRoute
  '/operator': typeof OperatorRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/umap': typeof UmapRoute
  '/workflows': typeof WorkflowsRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRouteWithChildren
  '/plugins/actions': typeof PluginsActionsRoute
  '/actions': typeof ActionsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/plugins/$pluginId/$pageId': typeof PluginsPluginIdPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/authorize': typeof AuthorizeRoute
  '/datasets': typeof DatasetsRoute
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/lineage': typeof LineageRoute
  '/lotus': typeof LotusRoute
  '/lotus-playground': typeof LotusPlaygroundRoute
  '/onboarding': typeof OnboardingRoute
  '/operator': typeof OperatorRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/umap': typeof UmapRoute
  '/workflows': typeof WorkflowsRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRouteWithChildren
  '/plugins/actions': typeof PluginsActionsRoute
  '/actions': typeof ActionsIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/plugins/$pluginId/$pageId': typeof PluginsPluginIdPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/authorize': typeof AuthorizeRoute
  '/datasets': typeof DatasetsRoute
  '/debug': typeof DebugRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/lineage': typeof LineageRoute
  '/lotus': typeof LotusRoute
  '/lotus-playground': typeof LotusPlaygroundRoute
  '/onboarding': typeof OnboardingRoute
  '/operator': typeof OperatorRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/umap': typeof UmapRoute
  '/workflows': typeof WorkflowsRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRouteWithChildren
  '/plugins/actions': typeof PluginsActionsRoute
  '/actions/': typeof ActionsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/plugins/$pluginId/$pageId': typeof PluginsPluginIdPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/authorize'
    | '/datasets'
    | '/debug'
    | '/docs'
    | '/features'
    | '/help'
    | '/lineage'
    | '/lotus'
    | '/lotus-playground'
    | '/onboarding'
    | '/operator'
    | '/pipelines'
    | '/resources'
    | '/search'
    | '/settings'
    | '/umap'
    | '/workflows'
    | '/actions/$actionId'
    | '/images/$imageId'
    | '/pipelines/$pipelineId'
    | '/plugins/$pluginId'
    | '/plugins/actions'
    | '/actions'
    | '/pipelines/'
    | '/plugins/$pluginId/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/authorize'
    | '/datasets'
    | '/debug'
    | '/docs'
    | '/features'
    | '/help'
    | '/lineage'
    | '/lotus'
    | '/lotus-playground'
    | '/onboarding'
    | '/operator'
    | '/resources'
    | '/search'
    | '/settings'
    | '/umap'
    | '/workflows'
    | '/actions/$actionId'
    | '/images/$imageId'
    | '/pipelines/$pipelineId'
    | '/plugins/$pluginId'
    | '/plugins/actions'
    | '/actions'
    | '/pipelines'
    | '/plugins/$pluginId/$pageId'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/authorize'
    | '/datasets'
    | '/debug'
    | '/docs'
    | '/features'
    | '/help'
    | '/lineage'
    | '/lotus'
    | '/lotus-playground'
    | '/onboarding'
    | '/operator'
    | '/pipelines'
    | '/resources'
    | '/search'
    | '/settings'
    | '/umap'
    | '/workflows'
    | '/actions/$actionId'
    | '/images/$imageId'
    | '/pipelines/$pipelineId'
    | '/plugins/$pluginId'
    | '/plugins/actions'
    | '/actions/'
    | '/pipelines/'
    | '/plugins/$pluginId/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AuthorizeRoute: typeof AuthorizeRoute
  DatasetsRoute: typeof DatasetsRoute
  DebugRoute: typeof DebugRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpRoute: typeof HelpRoute
  LineageRoute: typeof LineageRoute
  LotusRoute: typeof LotusRoute
  LotusPlaygroundRoute: typeof LotusPlaygroundRoute
  OnboardingRoute: typeof OnboardingRoute
  OperatorRoute: typeof OperatorRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UmapRoute: typeof UmapRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ActionsActionIdRoute: typeof ActionsActionIdRoute
  ImagesImageIdRoute: typeof ImagesImageIdRoute
  PluginsPluginIdRoute: typeof PluginsPluginIdRouteWithChildren
  PluginsActionsRoute: typeof PluginsActionsRoute
  ActionsIndexRoute: typeof ActionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umap': {
      id: '/umap'
      path: '/umap'
      fullPath: '/umap'
      preLoaderRoute: typeof UmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotus-playground': {
      id: '/lotus-playground'
      path: '/lotus-playground'
      fullPath: '/lotus-playground'
      preLoaderRoute: typeof LotusPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotus': {
      id: '/lotus'
      path: '/lotus'
      fullPath: '/lotus'
      preLoaderRoute: typeof LotusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/actions/': {
      id: '/actions/'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/actions': {
      id: '/plugins/actions'
      path: '/plugins/actions'
      fullPath: '/plugins/actions'
      preLoaderRoute: typeof PluginsActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/images/$imageId': {
      id: '/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/$actionId': {
      id: '/actions/$actionId'
      path: '/actions/$actionId'
      fullPath: '/actions/$actionId'
      preLoaderRoute: typeof ActionsActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/$pageId': {
      id: '/plugins/$pluginId/$pageId'
      path: '/$pageId'
      fullPath: '/plugins/$pluginId/$pageId'
      preLoaderRoute: typeof PluginsPluginIdPageIdRouteImport
      parentRoute: typeof PluginsPluginIdRoute
    }
  }
}

interface PipelinesRouteChildren {
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

interface PluginsPluginIdRouteChildren {
  PluginsPluginIdPageIdRoute: typeof PluginsPluginIdPageIdRoute
}

const PluginsPluginIdRouteChildren: PluginsPluginIdRouteChildren = {
  PluginsPluginIdPageIdRoute: PluginsPluginIdPageIdRoute,
}

const PluginsPluginIdRouteWithChildren = PluginsPluginIdRoute._addFileChildren(
  PluginsPluginIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AuthorizeRoute: AuthorizeRoute,
  DatasetsRoute: DatasetsRoute,
  DebugRoute: DebugRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  HelpRoute: HelpRoute,
  LineageRoute: LineageRoute,
  LotusRoute: LotusRoute,
  LotusPlaygroundRoute: LotusPlaygroundRoute,
  OnboardingRoute: OnboardingRoute,
  OperatorRoute: OperatorRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UmapRoute: UmapRoute,
  WorkflowsRoute: WorkflowsRoute,
  ActionsActionIdRoute: ActionsActionIdRoute,
  ImagesImageIdRoute: ImagesImageIdRoute,
  PluginsPluginIdRoute: PluginsPluginIdRouteWithChildren,
  PluginsActionsRoute: PluginsActionsRoute,
  ActionsIndexRoute: ActionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
